---
- name:  polemarch | Install dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items:
    - python
    - curl

- name:  polemarch | Download libssl1.0-dev for Debian Stretch
  get_url:
    url: "http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb"
    dest: /tmp
  when: ansible_distribution_major_version == '9'

- name: polemarch | Install libssl1.0-dev for Debian Stretch
  apt:
    deb: "/tmp/libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb"
  when: ansible_distribution_major_version == '9'

- name: polemarch | Check if polemarch is installed
  command: dpkg-query -W polemarch
  register: polemarch_check_deb
  failed_when: polemarch_check_deb.rc > 1
  changed_when: polemarch_check_deb.rc == 1
  become: true

- name: polemarch | Download install file
  get_url:
    url: "{{ polemarch_download_url }}{{ polemarch_debian_package_name }}"
    dest: /tmp
  when: polemarch_version not in polemarch_check_deb.stdout

- name: polemarch | Install polemarch
  apt:
    deb: "/tmp/{{ polemarch_debian_package_name }}"
  notify:
    - restart polemarch
    - restart polemarch worker
  when: polemarch_version not in polemarch_check_deb.stdout
  become: true

- file: dest=/opt/polemarch/lib/python2.7/site-packages/polemarch/projects owner=polemarch group=polemarch mode=0755 recurse=yes

- name: polemarch | configure
  lineinfile:
    dest: "/etc/polemarch/settings.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
    state: present
  with_items:
    - regexp: "# debug = true"
      line: "debug = {{ polemarch_config_debug }}"
      insertafter: ""
    - regexp: "# timezone = UTC"
      line: "timezone = {{ polemarch_config_timezone }}"
      insertafter: ""
    - regexp: "# engine = django.db.backends.sqlite3"
      line: "engine = {{ polemarch_config_db_engine }}"
      insertafter: ""
    - regexp: "# name = {HOME}/db.sqlite3"
      line: "name = {{ polemarch_config_db_name }}"
      insertafter: ""
    - regexp: "^user.?=.+$"
      line: "user = {{ polemarch_config_db_user }}"
      insertafter: "name = {{ polemarch_config_db_name }}"
    - regexp: "^password.?=.+$"
      line: "password = {{ polemarch_config_db_password }}"
      insertafter: "user = {{ polemarch_config_db_user }}"
    - regexp: "^host.?=.+$"
      line: "host = {{ polemarch_config_db_host }}"
      insertafter: "password = {{ polemarch_config_db_password }}"
    - regexp: "^port.?=.+$"
      line: "port = {{ polemarch_config_db_port }}"
      insertafter: "host = {{ polemarch_config_db_host }}"
    - regexp: "# backend = django.core.cache.backends.filebased.FileBasedCache"
      line: "backend = {{ polemarch_config_cache_engine }}"
      insertafter: ""
    - regexp: "# location = {TMP}/polemarch_django_cache{PY}"
      line: "location = {{ polemarch_config_cache_location }}"
      insertafter: ""
    - regexp: "# backend = django.core.cache.backends.filebased.FileBasedCache"
      line: "backend = {{ polemarch_config_cache_engine }}"
      insertafter: ""
    - regexp: "# location = {TMP}/polemarch_django_cache_locks{PY}"
      line: "location = {{ polemarch_config_cache_location }}"
      insertafter: ""
  when: polemarch_version not in polemarch_check_deb.stdout
  notify:
    - restart polemarch
    - restart polemarch worker

- name: polemarch | Create symlink
  file:
    src: /opt/polemarch/bin/polemarchctl
    dest: /usr/bin/polemarch
    state: link
  become: true

- name: polemarch | Migrate database
  command: /usr/bin/polemarch migrate
  become: true
  notify:
    - restart polemarch
    - restart polemarch worker
  when: polemarch_version not in polemarch_check_deb.stdout
