---
- name: polemarch | Configure Debian
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: polemarch | Configure Redhat
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'